# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-29 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_1', '0002_auto_20161221_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(),
        ),
    ]
